### ISSUE TITLE
Issues on page tips and tricks

### ISSUE THREAD

**Issue by neshatmoslehi** [andreashlarsen/SAStutorials#14]
Hi,

I spotted typos on the page: tips and tricks, and the link to the example doesn't work. See snapshots below.
![typos](https://github.com/user-attachments/assets/9e9728ea-4d39-4d2a-94a8-8228f081c253)
![issuewithlinktoexample](https://github.com/user-attachments/assets/a4d8fe91-9a2d-4ac6-874b-58b834c8b5e9)

**Comment by andreashlarsen** [comment]
thank you! they have been corrected
